//
//  WorldViewController.swift
//  WorldMatrix
//
//  Created by Alexandre Joly on 14/10/15.
//  Copyright © 2015 KiloKilo GmbH. All rights reserved.
//

import UIKit
import MapKit

class WorldViewController: UIViewController {

    @IBOutlet weak var worldMatrixView: WorldMatrixView!
    var worldArray:Array<WorldCharacteristic> = []

    override func viewDidLoad() {
        super.viewDidLoad()

        setupWorldArray()

        let matrix = Matrix<WorldCharacteristic>(columns: 100, array: worldArray)
        worldMatrixView.mapMatrix = matrix
//        worldMatrixView.mapCutting = MapCutting.Custom(north: 82.4, west: -179.99, south: -60, east: 180)
        worldMatrixView.mapCutting = MapCutting.World

        let newYork = CLLocationCoordinate2DMake(40.730610, -73.935242)
        worldMatrixView.setCharacteristic(.Marker, forCoordinate: newYork)

        let zurich = CLLocationCoordinate2DMake(47.367347, 8.5500025)
        worldMatrixView.setCharacteristic(.Marker, forCoordinate: zurich)

        let sydney = CLLocationCoordinate2DMake(-33.865143, 151.209900)
        worldMatrixView.setCharacteristic(.Marker, forCoordinate: sydney)

        let havana = CLLocationCoordinate2DMake(23.1333333333, -82.3833333333)
        worldMatrixView.setCharacteristic(.Marker, forCoordinate: havana)

        let rome = CLLocationCoordinate2DMake(41.9, 12.4833333)
        worldMatrixView.setCharacteristic(.Marker, forCoordinate: rome)

    }

    func setupWorldArray() {
        worldArray += [.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean]
        worldArray += [.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean]
        worldArray += [.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean]
        worldArray += [.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean]
        worldArray += [.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean]
        worldArray += [.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean]
        worldArray += [.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean]
        worldArray += [.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Land,.Ocean,.Land,.Land,.Land,.Ocean,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean]
        worldArray += [.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean]
        worldArray += [.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean]
        worldArray += [.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean]
        worldArray += [.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Ocean,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean]
        worldArray += [.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Ocean,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean]
        worldArray += [.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Ocean,.Land,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean]
        worldArray += [.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Ocean,.Ocean,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Ocean,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean]
        worldArray += [.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Ocean,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean]
        worldArray += [.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Ocean,.Land,.Ocean,.Land,.Ocean,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean]
        worldArray += [.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Ocean,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean]
        worldArray += [.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean]
        worldArray += [.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Ocean,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Ocean,.Ocean,.Ocean,.Land,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean]
        worldArray += [.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Land,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean]
        worldArray += [.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Land,.Ocean,.Land,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Ocean,.Ocean,.Ocean,.Land,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Land,.Land,.Land,.Land,.Land,.Ocean,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean]
        worldArray += [.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Land,.Land,.Land,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Ocean,.Ocean,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Land,.Land,.Ocean]
        worldArray += [.Land,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Ocean,.Land,.Ocean,.Ocean,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Land,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land]
        worldArray += [.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land]
        worldArray += [.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Ocean,.Land,.Land,.Land,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land]
        worldArray += [.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Land,.Ocean,.Ocean,.Ocean,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land]
        worldArray += [.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Ocean,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Land,.Land,.Land,.Ocean]
        worldArray += [.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Land,.Land,.Land,.Ocean,.Ocean]
        worldArray += [.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean]
        worldArray += [.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean]
        worldArray += [.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Ocean,.Ocean,.Land,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean]
        worldArray += [.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Ocean,.Land,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean]
        worldArray += [.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean]
        worldArray += [.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean]
        worldArray += [.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Land,.Ocean,.Land,.Land,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean]
        worldArray += [.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Land,.Ocean,.Land,.Ocean,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Land,.Land,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean]
        worldArray += [.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Ocean,.Ocean,.Land,.Ocean,.Land,.Land,.Land,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean]
        worldArray += [.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Ocean,.Ocean,.Ocean,.Land,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean]
        worldArray += [.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean]
        worldArray += [.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Land,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean]
        worldArray += [.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean]
        worldArray += [.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean]
        worldArray += [.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean]
        worldArray += [.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Ocean,.Ocean,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Land,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean]
        worldArray += [.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean]
        worldArray += [.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Ocean,.Ocean,.Ocean,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Ocean,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean]
        worldArray += [.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean]
        worldArray += [.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean]
        worldArray += [.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Ocean,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean]
        worldArray += [.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Ocean,.Land,.Ocean,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean]
        worldArray += [.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean]
        worldArray += [.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean]
        worldArray += [.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Ocean,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean]
        worldArray += [.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Ocean,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean]
        worldArray += [.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean]
        worldArray += [.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean]
        worldArray += [.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean]
        worldArray += [.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean]
        worldArray += [.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean]
        worldArray += [.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean]
        worldArray += [.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean]
        worldArray += [.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean]
        worldArray += [.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Ocean,.Ocean]
        worldArray += [.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean]
        worldArray += [.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean]
        worldArray += [.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean]
        worldArray += [.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean]
        worldArray += [.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean]
        worldArray += [.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean]
        worldArray += [.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean]
        worldArray += [.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean]
        worldArray += [.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean]
        worldArray += [.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean]
        worldArray += [.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Ocean,.Ocean,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean]
        worldArray += [.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean]
        worldArray += [.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean]
        worldArray += [.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean]
        worldArray += [.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean]
        worldArray += [.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean]
        worldArray += [.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Ocean,.Land,.Ocean,.Ocean,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean]
        worldArray += [.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Ocean,.Ocean,.Ocean,.Land,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean]
        worldArray += [.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean]
        worldArray += [.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean]
        worldArray += [.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean]
        worldArray += [.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean]
        worldArray += [.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean]
        worldArray += [.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Ocean,.Ocean,.Land,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean]
        worldArray += [.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean]
        worldArray += [.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Land,.Ocean,.Ocean,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean]
        worldArray += [.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean]
        worldArray += [.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Land,.Ocean,.Ocean,.Ocean,.Ocean,.Ocean,.Land]
    }

}
